version: '3.8'
services:
  wine-app:
    image: ghcr.io/codeit-21-part-3-team-3/wine:latest
    container_name: wine-next-service
    restart: unless-stopped
    ports:
      - '2133:3000'
    environment:
      - API_URL=${API_URL}
      - NODE_ENV=production
    volumes:
      - ./next-cache:/app/.next/cache
    restart: always
